[project]
name = "airbyte-cortex-service"
version = "0.1.0"
description = "AI-ready data pre-processing for Airbyte."
authors = [
    {name = "Kai",email = "ngominhkhoa2006@gmail.com"}
]
readme = "README.md"
requires-python = "^3.11"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
